version: "3.8"

services:
  adventurers-guild:
    image: danielhuglen/adventurers-guild:latest
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - EDITOR_PASSWORD=${EDITOR_PASSWORD}
    container_name: adventurers-guild
    restart: always
    ports:
      - "8081:4000"
    volumes:
      - app_data:/app/data

volumes:
  app_data: